dunno:
  tranche_age:
    type: int
    range: [0, 3]
  sexe_surrepresente:
    type: choice
    enum: [h, f]
  source:
    type: choice
    enum: ["solen-2019", "solen-2020", "egapro"]

entreprise:
  nom:
    type: string
  effectif:
    type: int
  annee:
    type: int
  periode:
    type: range

salaries:
  ages: range
  nombre_femmes: int
  nombre_hommes: int
